use_frameworks!

target 'RYRCalendar_Example' do
  pod 'RYRCalendar', :path => '../'

  target 'RYRCalendar_Tests' do
    inherit! :search_paths
    
    pod 'RYRCalendar', :path => '../'
    
  end
end
